version: '3.8'

services:
  test:
    image: dhohirp/pyspark-jupyter
    deploy:
      replicas: 1
    ports:
      - "38003:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
