apiVersion: v1
kind: Service
metadata:
  name: isolate-jupyter-$(SERVICE_NAME)-service
spec:
  selector:
    app: isolate-jupyter-$(SERVICE_NAME)
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort
